=== RUB-Informatik-im-Bauwesen/OpenBimRL/schema/OpenBimRL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
OpenBimRL (c) by Lehrstuhl für Informatik im Bauwesen, Ruhr-Universität Bochum, 2022

OpenBimRL is licensed under a
Creative Commons Attribution 4.0 International License.

You should have received a copy of the license along with this
work. If not, see <http://creativecommons.org/licenses/by/4.0/>.
-->
<schema targetNamespace="http://inf.bi.rub.de/OpenBimRL" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://inf.bi.rub.de/OpenBimRL">

    <element name="BIMRule" type="tns:BIMRuleType">
    </element>

    <complexType name="InputType">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    	<attribute name="typeHint" type="string"></attribute>
    	<attribute name="collectionType" type="string"></attribute>
    	<attribute name="required" type="string"></attribute>
    </complexType>

    <complexType name="OutputType">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>
    <complexType name="NodeType">
    	<sequence>
    		<element name="Description" type="string" maxOccurs="1"
    			minOccurs="0" nillable="true">
    		</element>
    		<element minOccurs="0" maxOccurs="1" name="Inputs">
    			<complexType>
    				<sequence minOccurs="1" maxOccurs="unbounded">
    					<element name="Input" type="tns:InputType"
    						maxOccurs="unbounded" minOccurs="1">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    		<element minOccurs="0" maxOccurs="1" name="Outputs">
    			<complexType>
    				<sequence>
    					<element name="Output" type="tns:OutputType"
    						maxOccurs="unbounded" minOccurs="1">
    					</element>
    				</sequence>
    			</complexType>
    		</element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="function" type="string"></attribute>
    	<attribute name="alias" type="string"></attribute>
    </complexType>
    <complexType name="BIMRuleType">
    	<sequence>
    		<element name="Precalculations"
    			type="tns:PrecalculationsType" maxOccurs="1" minOccurs="0">
    		</element>
    		<element name="ModelCheck" type="tns:ModelCheckType"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="schemaVersion" type="string" use="required"></attribute>
    </complexType>

    <complexType name="ModelCheckType">
    	<sequence>
    		<element name="RuleIdentifiers"
    			type="tns:RuleIdentifiersType">
    		</element>
    		<element name="ModelSubChecks"
    			type="tns:ModelSubChecksType">
    		</element>
    		<element name="ResultSets" 
    			type="tns:ResultSetsType">
    		</element>
        </sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="RulesType">
    	<choice maxOccurs="unbounded" minOccurs="1">
    		<element name="Rule" type="tns:RuleType">
    			<unique name="ruleUniqueLabel">
				    <selector xpath="tns:RuleType" /> 
				    <field xpath="@label" /> 
			    </unique>
    		</element>
    		<element ref="tns:Rules">
    		</element>
    	</choice>
    	<attribute name="operator" type="string"></attribute>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="RuleType">
    	<attribute name="label" type="string"></attribute>
        <attribute name="quantifier" type="string"></attribute>
        <attribute name="operator" type="string"></attribute>
    	<attribute name="operand1" type="string"></attribute>
    	<attribute name="operand2" type="string"></attribute>
    	<attribute name="filter" type="string"></attribute>
    </complexType>

    <complexType name="RuleIdentifiersType">
    	<sequence>
    		<element name="RuleIdentifier" type="tns:RuleIdentifierType" maxOccurs="unbounded" minOccurs="1">
			    <unique name="ruleIdentifierUniqueLabel">
				    <selector xpath="tns:RuleIdentifierType" /> 
				    <field xpath="@label" /> 
			    </unique>
    		</element>
    	</sequence>
    </complexType>

    <complexType name="RuleIdentifierType">
    	<sequence>
    		<element name="Message" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="source" type="string" use="required"></attribute>
    	<attribute name="sourceHandle" type="int" use="required"></attribute>
    	<attribute name="label" type="string" use="required"></attribute>
    </complexType>
    
    <complexType name="ModelSubChecksType">
    	<sequence>
    		<element name="ModelSubCheck"
    			type="tns:ModelSubCheckType" maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>
    
    <complexType name="ModelSubCheckType">
    	<sequence>
    		<element name="Applicability" type="tns:ApplicabilityType"></element>
    		<element name="Rules" type="tns:RulesType"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>

    <complexType name="ApplicabilityType">
    	<choice>
    		<element ref="tns:Rule"></element>
    	</choice>
    </complexType>
    
    <complexType name="ResultSetType">
    	<attribute name="name" type="string"></attribute>
        <attribute name="elements" type="string"></attribute>
    	<attribute name="filter" type="string"></attribute>
    </complexType>
    
    <complexType name="ResultSetsType">
    	<sequence>
    		<element name="ResultSet" type="tns:ResultSetType" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    

    <element name="Rule" type="tns:RuleType"></element>

    <element name="Rules" type="tns:RulesType"></element>

    <complexType name="PrecalculationsType">
    	<choice maxOccurs="unbounded" minOccurs="1">
    		<element name="Node" type="tns:NodeType">
    		</element>
    		<element name="Edge" type="tns:EdgeType"></element>
    	</choice>
    </complexType>

    <complexType name="EdgeType">
    	<attribute name="id" type="string"></attribute>
    	<attribute name="source" type="string"></attribute>
    	<attribute name="sourceHandle" type="int"></attribute>
    	<attribute name="target" type="string"></attribute>
    	<attribute name="targetHandle" type="int"></attribute>
    </complexType>
</schema>

=== RUB-Informatik-im-Bauwesen/OpenBimRL/examples/OpenBimRL samples/Formelle Prüfung von tragfähikeits Eigenschaften von Wänden.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:BIMRule schemaVersion="0.1" xmlns:tns="http://inf.bi.rub.de/OpenBimRL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://inf.bi.rub.de/OpenBimRL OpenBimRL.xsd">
	<tns:Precalculations>
		<tns:Node id="85d5009c-f8dc-1ccf-66c8-ce610713793a" function="ifc.getProperty" alias="Example Text Here">
			<tns:Inputs>
				<tns:Input name="IfcElement"/>
				<tns:Input name="PropertySetName"/>
				<tns:Input name="PropertyName"/>
			</tns:Inputs>
			<tns:Outputs>
				<tns:Output name="value"/>
			</tns:Outputs>
		</tns:Node>
		<tns:Node id="6ba3cccc-4a01-bc7a-fd91-e3ca9a717c52" function="input.textInput">
			<tns:Outputs>
				<tns:Output name="text" value="Pset_WallCommon"/>
			</tns:Outputs>
		</tns:Node>
		<tns:Node id="c37f31a8-265b-9fab-3363-67a516e49f96" function="input.textInput">
			<tns:Outputs>
				<tns:Output name="text" value="LoadBearing"/>
			</tns:Outputs>
		</tns:Node>
		<tns:Node id="bb426f64-8658-e235-e8fa-aec86ff5d78c" function="input.textInput">
			<tns:Outputs>
				<tns:Output name="text" value="IfcWall"/>
			</tns:Outputs>
		</tns:Node>
		<tns:Node id="bc2a7431-9376-db5d-a12a-fe48e83bddbd" function="ifc.filterByElement" alias="Example Text Here">
			<tns:Inputs>
				<tns:Input name="IfcType"/>
			</tns:Inputs>
			<tns:Outputs>
				<tns:Output name="IfcElement_List"/>
			</tns:Outputs>
		</tns:Node>
		<tns:Node id="6d2cd2a8-079f-6108-53e8-3cc8553c7748" function="ifc.getAllPropertySetInformation" alias="Example Text Here">
			<tns:Inputs>
				<tns:Input name="IfcElement"/>
			</tns:Inputs>
			<tns:Outputs>
				<tns:Output name="Map of PropertyInfo"/>
			</tns:Outputs>
		</tns:Node>
		<tns:Node id="6aae2d89-1437-df28-ebdf-72b8dad84b77" function="input.textInput">
			<tns:Outputs>
				<tns:Output name="text" value="IfcObject"/>
			</tns:Outputs>
		</tns:Node>
		<tns:Node id="a018968c-2131-2498-85eb-af68d568c668" function="ifc.filterByElement" alias="Example Text Here">
			<tns:Inputs>
				<tns:Input name="IfcType"/>
			</tns:Inputs>
			<tns:Outputs>
				<tns:Output name="IfcElement_List"/>
			</tns:Outputs>
		</tns:Node>
		<tns:Node id="38e85418-b007-29d8-3068-4ffd1a989f75" function="ifc.getIfcType" alias="Example Text Here">
			<tns:Inputs>
				<tns:Input name="IfcElement"/>
			</tns:Inputs>
			<tns:Outputs>
				<tns:Output name="IfcType"/>
			</tns:Outputs>
		</tns:Node>
		<tns:Edge id="953a5a9a-d90f-d80b-8b3a-85586e15b885" source="6ba3cccc-4a01-bc7a-fd91-e3ca9a717c52" sourceHandle="0" target="85d5009c-f8dc-1ccf-66c8-ce610713793a" targetHandle="1"/>
		<tns:Edge id="8bee1359-1d92-5285-2656-99e8cdcfaa3d" source="c37f31a8-265b-9fab-3363-67a516e49f96" sourceHandle="0" target="85d5009c-f8dc-1ccf-66c8-ce610713793a" targetHandle="2"/>
		<tns:Edge id="459378e2-3ee4-92ea-4d46-54dd0b3676cc" source="bb426f64-8658-e235-e8fa-aec86ff5d78c" sourceHandle="0" target="bc2a7431-9376-db5d-a12a-fe48e83bddbd" targetHandle="0"/>
		<tns:Edge id="484671e2-884e-364f-574e-c869de166e12" source="bc2a7431-9376-db5d-a12a-fe48e83bddbd" sourceHandle="0" target="85d5009c-f8dc-1ccf-66c8-ce610713793a" targetHandle="0"/>
		<tns:Edge id="780178d2-4bf2-a9ec-9e78-453dcc07e65d" source="6aae2d89-1437-df28-ebdf-72b8dad84b77" sourceHandle="0" target="a018968c-2131-2498-85eb-af68d568c668" targetHandle="0"/>
		<tns:Edge id="0cd89868-84ce-d26c-e0a8-0808ded60de8" source="a018968c-2131-2498-85eb-af68d568c668" sourceHandle="0" target="6d2cd2a8-079f-6108-53e8-3cc8553c7748" targetHandle="0"/>
		<tns:Edge id="adc8ab56-8068-e44a-2598-bde8e3d82e0c" source="a018968c-2131-2498-85eb-af68d568c668" sourceHandle="0" target="38e85418-b007-29d8-3068-4ffd1a989f75" targetHandle="0"/>
	</tns:Precalculations>
	<tns:ModelCheck name="Formelle Prüfung von tragfähikeits Eigenschaften von Wänden">
		<tns:RuleIdentifiers>
			<tns:RuleIdentifier label="propertyValue" source="85d5009c-f8dc-1ccf-66c8-ce610713793a" sourceHandle="0"/>
			<tns:RuleIdentifier label="ifcWallEntities" source="bc2a7431-9376-db5d-a12a-fe48e83bddbd" sourceHandle="0"/>
			<tns:RuleIdentifier label="propertyInfos" source="6d2cd2a8-079f-6108-53e8-3cc8553c7748" sourceHandle="0"/>
			<tns:RuleIdentifier label="ifcTypes" source="38e85418-b007-29d8-3068-4ffd1a989f75" sourceHandle="0"/>
			<tns:RuleIdentifier label="ifcEntities" source="a018968c-2131-2498-85eb-af68d568c668" sourceHandle="0"/>
		</tns:RuleIdentifiers>
		<tns:ModelSubChecks>
			<tns:ModelSubCheck name="Check PropertySet by Values">
				<tns:Rules label="77dd6850-f1d7-4c13-81e0-2de33fbf06cc" operator="or">
					<tns:Rule label="check01" quantifier="exists" operator="equals" operand1="propertyValue" operand2="true"/>
					<tns:Rule label="check02" quantifier="exists" operator="equals" operand1="propertyValue" operand2="false"/>
				</tns:Rules>
			</tns:ModelSubCheck>
			<tns:ModelSubCheck name="Check PropertySet by PropertyInfos">
				<tns:Rules label="3129cd4c-e3d0-4c02-8250-01a4da1c1508" operator="and">
					<tns:Rule label="check03" quantifier="exists" operator="equals" operand1="propertyInfos" operand2="Pset_WallCommon:LoadBearing:true"/>
					<tns:Rule label="check04" quantifier="exists" operator="equals" operand1="propertyInfos" operand2="Pset_WallCommon:LoadBearing:false"/>
					<tns:Rule label="check05" quantifier="exists" operator="equals" operand1="ifcTypes" operand2="IfcWall"/>
				</tns:Rules>
			</tns:ModelSubCheck>
		</tns:ModelSubChecks>
		<tns:ResultSets>
			<tns:ResultSet name="PropertySet by Values [true]" elements="ifcWallEntities" filter="check01"/>
			<tns:ResultSet name="PropertySet by Values [false]" elements="ifcWallEntities" filter="check02"/>
			<tns:ResultSet name="PropertySet by PropertyInfos Selection [true]" elements="ifcEntities" filter="check05 AND check03"/>
			<tns:ResultSet name="PropertySet by PropertyInfos Selection [false]" elements="ifcEntities" filter="check05 AND check04"/>
			<tns:ResultSet name="PropertySet by PropertyInfos Filtered Entities" elements="ifcEntities" filter="check05"/>
		</tns:ResultSets>
	</tns:ModelCheck>
</tns:BIMRule>
